import type { Project } from "./types"

export const projects: Project[] = [
  {
    id: 1,
    title: "Modern Textile Manufacturing Plant",
    category: "Industry",
    region: "Tashkent",
    image: "/modern-textile-factory.png",
    initiator: "Uzbek Textiles LLC",
    contact: "+998 71 234 56 78",
    goal: "Establish a state-of-the-art textile manufacturing facility producing high-quality fabrics for domestic and export markets",
    productionCapacity: "5,000 tons per year",
    jobsCreated: 250,
    implementationDeadline: "December 2025",
    totalInvestment: 15000000,
    bankLoan: 10000000,
    netProfit: 3500000,
    bank: "National Bank of Uzbekistan",
    description:
      "A cutting-edge textile manufacturing plant equipped with modern machinery and sustainable production methods.",
  },
  {
    id: 2,
    title: "Organic Fruit Processing Facility",
    category: "Agriculture",
    region: "Samarkand",
    image: "/fruit-processing-facility.jpg",
    initiator: "Samarkand Agro Group",
    contact: "+998 66 123 45 67",
    goal: "Process and package organic fruits for local and international markets with focus on quality and sustainability",
    productionCapacity: "3,000 tons per year",
    jobsCreated: 180,
    implementationDeadline: "June 2025",
    totalInvestment: 8000000,
    bankLoan: 5500000,
    netProfit: 2000000,
    bank: "Agrobank",
    description:
      "Modern facility for processing organic fruits with international quality certifications and eco-friendly packaging.",
  },
  {
    id: 3,
    title: "Digital Marketing Agency Hub",
    category: "Services",
    region: "Tashkent",
    image: "/modern-office-digital-agency.jpg",
    initiator: "Digital Uzbekistan",
    contact: "+998 71 345 67 89",
    goal: "Provide comprehensive digital marketing services to local businesses and help them expand online presence",
    productionCapacity: "100+ clients per year",
    jobsCreated: 75,
    implementationDeadline: "March 2025",
    totalInvestment: 2000000,
    bankLoan: 1200000,
    netProfit: 800000,
    bank: "Ipoteka Bank",
    description:
      "Full-service digital marketing agency offering SEO, social media management, and web development services.",
  },
  {
    id: 4,
    title: "Automotive Parts Manufacturing",
    category: "Industry",
    region: "Andijan",
    image: "/automotive-parts-factory.jpg",
    initiator: "Andijan Auto Parts",
    contact: "+998 74 234 56 78",
    goal: "Manufacture high-quality automotive parts for domestic vehicle assembly and export to neighboring countries",
    productionCapacity: "50,000 units per year",
    jobsCreated: 320,
    implementationDeadline: "September 2025",
    totalInvestment: 20000000,
    bankLoan: 14000000,
    netProfit: 4500000,
    bank: "Asaka Bank",
    description:
      "Advanced manufacturing facility producing automotive components with international quality standards.",
  },
  {
    id: 5,
    title: "Greenhouse Vegetable Complex",
    category: "Agriculture",
    region: "Bukhara",
    image: "/modern-greenhouse-vegetables.jpg",
    initiator: "Bukhara Green Farm",
    contact: "+998 65 123 45 67",
    goal: "Year-round production of fresh vegetables using modern greenhouse technology and sustainable farming practices",
    productionCapacity: "2,500 tons per year",
    jobsCreated: 150,
    implementationDeadline: "August 2025",
    totalInvestment: 6000000,
    bankLoan: 4000000,
    netProfit: 1500000,
    bank: "Agrobank",
    description: "Climate-controlled greenhouse complex for sustainable vegetable production throughout the year.",
  },
  {
    id: 6,
    title: "IT Training and Development Center",
    category: "Services",
    region: "Fergana",
    image: "/modern-it-training-center.jpg",
    initiator: "Fergana Tech Academy",
    contact: "+998 73 234 56 78",
    goal: "Provide professional IT training and certification programs to develop skilled workforce for tech industry",
    productionCapacity: "1,000 students per year",
    jobsCreated: 45,
    implementationDeadline: "April 2025",
    totalInvestment: 1500000,
    bankLoan: 900000,
    netProfit: 600000,
    bank: "Ipoteka Bank",
    description: "Modern training facility offering courses in programming, data science, and digital technologies.",
  },
  {
    id: 7,
    title: "Pharmaceutical Production Plant",
    category: "Industry",
    region: "Tashkent",
    image: "/pharmaceutical-manufacturing-plant.png",
    initiator: "Pharma Uzbekistan",
    contact: "+998 71 456 78 90",
    goal: "Manufacture essential medicines and pharmaceutical products to meet domestic demand and reduce imports",
    productionCapacity: "10 million units per year",
    jobsCreated: 280,
    implementationDeadline: "November 2025",
    totalInvestment: 25000000,
    bankLoan: 17000000,
    netProfit: 5500000,
    bank: "National Bank of Uzbekistan",
    description: "GMP-certified pharmaceutical plant producing high-quality medicines for local and regional markets.",
  },
  {
    id: 8,
    title: "Dairy Processing Complex",
    category: "Agriculture",
    region: "Kashkadarya",
    image: "/modern-dairy-processing-facility.jpg",
    initiator: "Kashkadarya Dairy",
    contact: "+998 75 123 45 67",
    goal: "Process fresh milk into various dairy products including cheese, yogurt, and butter for regional distribution",
    productionCapacity: "4,000 tons per year",
    jobsCreated: 200,
    implementationDeadline: "July 2025",
    totalInvestment: 9000000,
    bankLoan: 6000000,
    netProfit: 2200000,
    bank: "Agrobank",
    description:
      "State-of-the-art dairy processing facility with cold chain infrastructure and quality control systems.",
  },
  {
    id: 9,
    title: "Logistics and Warehousing Center",
    category: "Services",
    region: "Namangan",
    image: "/modern-warehouse-logistics-center.jpg",
    initiator: "Namangan Logistics",
    contact: "+998 69 234 56 78",
    goal: "Provide comprehensive logistics and warehousing solutions for businesses in the Fergana Valley region",
    productionCapacity: "50,000 m² storage capacity",
    jobsCreated: 120,
    implementationDeadline: "May 2025",
    totalInvestment: 7000000,
    bankLoan: 4500000,
    netProfit: 1800000,
    bank: "Ipoteka Bank",
    description: "Modern logistics hub with temperature-controlled storage and advanced inventory management systems.",
  },
  {
    id: 10,
    title: "Furniture Manufacturing Workshop",
    category: "Industry",
    region: "Samarkand",
    image: "/modern-furniture-factory.jpg",
    initiator: "Samarkand Furniture",
    contact: "+998 66 345 67 89",
    goal: "Produce high-quality furniture for residential and commercial markets using sustainable materials",
    productionCapacity: "15,000 units per year",
    jobsCreated: 160,
    implementationDeadline: "October 2025",
    totalInvestment: 5000000,
    bankLoan: 3500000,
    netProfit: 1200000,
    bank: "Asaka Bank",
    description: "Modern furniture manufacturing facility with CNC machinery and eco-friendly production processes.",
  },
  {
    id: 11,
    title: "Poultry Farm Complex",
    category: "Agriculture",
    region: "Surkhandarya",
    image: "/modern-poultry-farm.png",
    initiator: "Surkhan Poultry",
    contact: "+998 76 123 45 67",
    goal: "Large-scale poultry farming for meat and egg production with modern biosecurity measures",
    productionCapacity: "5 million eggs per year",
    jobsCreated: 140,
    implementationDeadline: "June 2025",
    totalInvestment: 4500000,
    bankLoan: 3000000,
    netProfit: 1100000,
    bank: "Agrobank",
    description: "Automated poultry farm with climate control and veterinary care facilities.",
  },
  {
    id: 12,
    title: "Tourism and Hospitality Training Center",
    category: "Services",
    region: "Bukhara",
    image: "/hospitality-training-center.jpg",
    initiator: "Bukhara Tourism Academy",
    contact: "+998 65 234 56 78",
    goal: "Train hospitality professionals to support the growing tourism industry in Uzbekistan",
    productionCapacity: "500 students per year",
    jobsCreated: 35,
    implementationDeadline: "March 2025",
    totalInvestment: 1200000,
    bankLoan: 700000,
    netProfit: 450000,
    bank: "Ipoteka Bank",
    description: "Professional training center for hotel management, culinary arts, and tour guiding.",
  },
]
