import type { Project } from "./types"

export const projects: Project[] = [
  {
    id: 1,
    title: "Textile Production Plant",
    category: "Industry",
    region: "Nukus",
    mahalla: "Qorauzy mahallesi",
    image: "/modern-textile-factory.png",
    initiator: "Karakalpak Textile Group",
    contact: "+998 61 234 56 78",
    goal: "Launch modern textile production with export potential to Kazakhstan and Turkmenistan",
    productionCapacity: "4,000 tons per year",
    jobsCreated: 210,
    implementationDeadline: "December 2025",
    totalInvestment: 13000000,
    bankLoan: 8500000,
    netProfit: 3200000,
    bank: "Qaraqalpaq Agrobank",
    description: "A modern textile factory equipped with automated weaving and dyeing lines.",
  },
  {
    id: 2,
    title: "Rice Processing Complex",
    category: "Agriculture",
    region: "Kegeyli",
    mahalla: "Qiziljar mahallesi",
    image: "/fruit-processing-facility.jpg",
    initiator: "Kegeyli Agro Group",
    contact: "+998 61 222 33 44",
    goal: "Process and package locally grown rice for domestic and export markets",
    productionCapacity: "3,500 tons per year",
    jobsCreated: 160,
    implementationDeadline: "June 2025",
    totalInvestment: 7000000,
    bankLoan: 5000000,
    netProfit: 1800000,
    bank: "Agrobank Qaraqalpaq bo‘limi",
    description: "Rice milling and packaging plant with modern sorting and cleaning technology.",
  },
  {
    id: 3,
    title: "IT Learning Hub",
    category: "Services",
    region: "Chimbay",
    mahalla: "Oltinsoy mahallesi",
    image: "/modern-it-training-center.jpg",
    initiator: "Chimbay Tech Center",
    contact: "+998 61 333 44 55",
    goal: "Provide coding and IT training to youth and small businesses",
    productionCapacity: "800 students per year",
    jobsCreated: 40,
    implementationDeadline: "March 2025",
    totalInvestment: 1200000,
    bankLoan: 800000,
    netProfit: 450000,
    bank: "Ipoteka Bank Nukus filial",
    description: "Training center for programming, web design, and digital skills.",
  },
  {
    id: 4,
    title: "Automotive Spare Parts Workshop",
    category: "Industry",
    region: "Taxtakupir",
    mahalla: "Bozatau mahallesi",
    image: "/automotive-parts-factory.jpg",
    initiator: "Taxtakupir Auto Parts",
    contact: "+998 61 444 55 66",
    goal: "Produce essential automotive components for local markets",
    productionCapacity: "25,000 units per year",
    jobsCreated: 130,
    implementationDeadline: "October 2025",
    totalInvestment: 6000000,
    bankLoan: 4000000,
    netProfit: 1500000,
    bank: "Asaka Bank Qaraqalpaq bo‘limi",
    description: "Workshop with CNC machines producing metal components for vehicles.",
  },
  {
    id: 5,
    title: "Greenhouse Tomato Complex",
    category: "Agriculture",
    region: "Turtkul",
    mahalla: "Berdaq mahallesi",
    image: "/modern-greenhouse-vegetables.jpg",
    initiator: "Turtkul Agro Farm",
    contact: "+998 61 555 66 77",
    goal: "Produce organic vegetables year-round using greenhouse technology",
    productionCapacity: "1,800 tons per year",
    jobsCreated: 120,
    implementationDeadline: "August 2025",
    totalInvestment: 5000000,
    bankLoan: 3500000,
    netProfit: 1300000,
    bank: "Agrobank",
    description: "Modern greenhouse facility for high-yield vegetable production.",
  },
  {
    id: 6,
    title: "Dairy Processing Plant",
    category: "Agriculture",
    region: "Kungrad",
    mahalla: "Qarakalpak mahallesi",
    image: "/modern-dairy-processing-facility.jpg",
    initiator: "Kungrad Dairy Co.",
    contact: "+998 61 666 77 88",
    goal: "Process milk into cheese, butter, and yogurt for local distribution",
    productionCapacity: "3,000 tons per year",
    jobsCreated: 180,
    implementationDeadline: "July 2025",
    totalInvestment: 8000000,
    bankLoan: 5000000,
    netProfit: 2000000,
    bank: "Agrobank Kungrad filial",
    description: "Facility equipped with modern milk processing and cold storage systems.",
  },
  {
    id: 7,
    title: "Furniture Production Workshop",
    category: "Industry",
    region: "Amudarya",
    mahalla: "Mangit mahallesi",
    image: "/modern-furniture-factory.jpg",
    initiator: "Amudarya Furniture Works",
    contact: "+998 61 777 88 99",
    goal: "Produce wooden furniture for schools, offices, and homes",
    productionCapacity: "10,000 units per year",
    jobsCreated: 90,
    implementationDeadline: "October 2025",
    totalInvestment: 4500000,
    bankLoan: 2800000,
    netProfit: 1100000,
    bank: "Asaka Bank",
    description: "Eco-friendly furniture workshop using locally sourced wood.",
  },
  {
    id: 8,
    title: "Tourism Development Center",
    category: "Services",
    region: "Muynak",
    mahalla: "Aral mahallesi",
    image: "/tourism-development-center.jpg",
    initiator: "Muynak Tourism Board",
    contact: "+998 61 888 99 00",
    goal: "Develop eco-tourism and cultural heritage programs in the Aral region",
    productionCapacity: "1,000 tourists per year",
    jobsCreated: 60,
    implementationDeadline: "May 2025",
    totalInvestment: 2500000,
    bankLoan: 1500000,
    netProfit: 700000,
    bank: "Ipoteka Bank",
    description: "Tourism center with guest facilities and eco-tourism programs around Aral Sea.",
  },
]

export type ProjectCategory = "Industry" | "Agriculture" | "Services"
